// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarm.proto

package SB.grpc;

public interface AlarmOnRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AlarmOnRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alarmonreqmessage = 1;</code>
   */
  java.lang.String getAlarmonreqmessage();
  /**
   * <code>string alarmonreqmessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getAlarmonreqmessageBytes();
}
