// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarm.proto

package SB.grpc;

public interface AlarmOffRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AlarmOffRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alarmoffreqmessage = 1;</code>
   */
  java.lang.String getAlarmoffreqmessage();
  /**
   * <code>string alarmoffreqmessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getAlarmoffreqmessageBytes();
}
