// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarm.proto

package SB.grpc;

public final class Alarm {
  private Alarm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AlarmOnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AlarmOnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIAlarmOnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIAlarmOnResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AlarmOffRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AlarmOffRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIAlarmOffResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIAlarmOffResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013alarm.proto\"+\n\016AlarmOnRequest\022\031\n\021alarm" +
      "onreqmessage\030\001 \001(\t\"/\n\022APIAlarmOnResponse" +
      "\022\031\n\021alarmonresmessage\030\001 \001(\t\"-\n\017AlarmOffR" +
      "equest\022\032\n\022alarmoffreqmessage\030\001 \001(\t\"1\n\023AP" +
      "IAlarmOffResponse\022\032\n\022alarmoffresmessage\030" +
      "\001 \001(\t2l\n\005alarm\022/\n\007alarmon\022\017.AlarmOnReque" +
      "st\032\023.APIAlarmOnResponse\0222\n\010alarmoff\022\020.Al" +
      "armOffRequest\032\024.APIAlarmOffResponseB\022\n\007S" +
      "B.grpcB\005AlarmP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AlarmOnRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AlarmOnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AlarmOnRequest_descriptor,
        new java.lang.String[] { "Alarmonreqmessage", });
    internal_static_APIAlarmOnResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_APIAlarmOnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIAlarmOnResponse_descriptor,
        new java.lang.String[] { "Alarmonresmessage", });
    internal_static_AlarmOffRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AlarmOffRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AlarmOffRequest_descriptor,
        new java.lang.String[] { "Alarmoffreqmessage", });
    internal_static_APIAlarmOffResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_APIAlarmOffResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIAlarmOffResponse_descriptor,
        new java.lang.String[] { "Alarmoffresmessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
