// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: curtains.proto

package SB.grpc;

public interface AllCOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AllC)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cAllrequest = 1;</code>
   */
  java.lang.String getCAllrequest();
  /**
   * <code>string cAllrequest = 1;</code>
   */
  com.google.protobuf.ByteString
      getCAllrequestBytes();
}
