// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarm.proto

package SB.grpc;

public interface APIAlarmOffResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APIAlarmOffResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alarmoffresmessage = 1;</code>
   */
  java.lang.String getAlarmoffresmessage();
  /**
   * <code>string alarmoffresmessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getAlarmoffresmessageBytes();
}
