// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarm.proto

package SB.grpc;

public interface APIAlarmOnResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APIAlarmOnResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alarmonresmessage = 1;</code>
   */
  java.lang.String getAlarmonresmessage();
  /**
   * <code>string alarmonresmessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getAlarmonresmessageBytes();
}
