// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: curtains.proto

package SB.grpc;

public interface APIAllCOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APIAllC)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cAllresponse = 1;</code>
   */
  java.lang.String getCAllresponse();
  /**
   * <code>string cAllresponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getCAllresponseBytes();
}
