// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: curtains.proto

package SB.grpc;

public interface APICResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APICResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cresponsemessage = 1;</code>
   */
  java.lang.String getCresponsemessage();
  /**
   * <code>string cresponsemessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getCresponsemessageBytes();

  /**
   * <code>string cresponsecode = 2;</code>
   */
  java.lang.String getCresponsecode();
  /**
   * <code>string cresponsecode = 2;</code>
   */
  com.google.protobuf.ByteString
      getCresponsecodeBytes();
}
