// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roomba.proto

package SB.grpc;

public interface APICleanSelectedRoomsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APICleanSelectedRoomsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string room = 1;</code>
   */
  java.lang.String getRoom();
  /**
   * <code>string room = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomBytes();

  /**
   * <code>int32 roomnumber = 2;</code>
   */
  int getRoomnumber();

  /**
   * <code>int32 roompercent = 3;</code>
   */
  int getRoompercent();
}
