// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roomba.proto

package SB.grpc;

public interface APICleanAllRoomsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APICleanAllRoomsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responsemessage = 1;</code>
   */
  java.lang.String getResponsemessage();
  /**
   * <code>string responsemessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponsemessageBytes();
}
