// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lights.proto

package SB.grpc;

public interface APILightsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APILightsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responsemessage = 1;</code>
   */
  java.lang.String getResponsemessage();
  /**
   * <code>string responsemessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponsemessageBytes();

  /**
   * <code>string responsecode = 2;</code>
   */
  java.lang.String getResponsecode();
  /**
   * <code>string responsecode = 2;</code>
   */
  com.google.protobuf.ByteString
      getResponsecodeBytes();
}
