// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lights.proto

package SB.grpc;

public interface APISwitchOffAllLightsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APISwitchOffAllLights)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string switchOffAllResponse = 1;</code>
   */
  java.lang.String getSwitchOffAllResponse();
  /**
   * <code>string switchOffAllResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getSwitchOffAllResponseBytes();
}
