// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: curtains.proto

package SB.grpc;

public interface CRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 cstatus = 1;</code>
   */
  int getCstatus();

  /**
   * <code>int32 croom = 2;</code>
   */
  int getCroom();
}
