// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: curtains.proto

package SB.grpc;

public final class Curtains {
  private Curtains() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APICResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APICResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AllC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AllC_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIAllC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIAllC_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016curtains.proto\"*\n\010CRequest\022\017\n\007cstatus\030" +
      "\001 \001(\005\022\r\n\005croom\030\002 \001(\005\"?\n\014APICResponse\022\030\n\020" +
      "cresponsemessage\030\001 \001(\t\022\025\n\rcresponsecode\030" +
      "\002 \001(\t\"\033\n\004AllC\022\023\n\013cAllrequest\030\001 \001(\t\"\037\n\007AP" +
      "IAllC\022\024\n\014cAllresponse\030\001 \001(\t2P\n\010curtains\022" +
      "#\n\007cswitch\022\t.CRequest\032\r.APICResponse\022\037\n\n" +
      "cswitchall\022\005.AllC\032\010.APIAllC0\001B\025\n\007SB.grpc" +
      "B\010CurtainsP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CRequest_descriptor,
        new java.lang.String[] { "Cstatus", "Croom", });
    internal_static_APICResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_APICResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APICResponse_descriptor,
        new java.lang.String[] { "Cresponsemessage", "Cresponsecode", });
    internal_static_AllC_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AllC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AllC_descriptor,
        new java.lang.String[] { "CAllrequest", });
    internal_static_APIAllC_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_APIAllC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIAllC_descriptor,
        new java.lang.String[] { "CAllresponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
