// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lights.proto

package SB.grpc;

public final class Lights {
  private Lights() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SwitchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SwitchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APILightsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APILightsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SwitchOffAllLights_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SwitchOffAllLights_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APISwitchOffAllLights_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APISwitchOffAllLights_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014lights.proto\"9\n\rSwitchRequest\022\024\n\014light" +
      "sstatus\030\001 \001(\005\022\022\n\nlightsroom\030\002 \001(\005\"B\n\021API" +
      "LightsResponse\022\027\n\017responsemessage\030\001 \001(\t\022" +
      "\024\n\014responsecode\030\002 \001(\t\"*\n\022SwitchOffAllLig" +
      "hts\022\024\n\014switchOffAll\030\001 \001(\t\"5\n\025APISwitchOf" +
      "fAllLights\022\034\n\024switchOffAllResponse\030\001 \001(\t" +
      "2|\n\006lights\0221\n\013lightswitch\022\016.SwitchReques" +
      "t\032\022.APILightsResponse\022?\n\016lightswitchall\022" +
      "\023.SwitchOffAllLights\032\026.APISwitchOffAllLi" +
      "ghts0\001B\023\n\007SB.grpcB\006LightsP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SwitchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SwitchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SwitchRequest_descriptor,
        new java.lang.String[] { "Lightsstatus", "Lightsroom", });
    internal_static_APILightsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_APILightsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APILightsResponse_descriptor,
        new java.lang.String[] { "Responsemessage", "Responsecode", });
    internal_static_SwitchOffAllLights_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SwitchOffAllLights_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SwitchOffAllLights_descriptor,
        new java.lang.String[] { "SwitchOffAll", });
    internal_static_APISwitchOffAllLights_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_APISwitchOffAllLights_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APISwitchOffAllLights_descriptor,
        new java.lang.String[] { "SwitchOffAllResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
