// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roomba.proto

package SB.grpc;

public final class Roomba {
  private Roomba() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CleanSelectedRooms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CleanSelectedRooms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APICleanSelectedRoomsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APICleanSelectedRoomsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CleanAllRooms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CleanAllRooms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APICleanAllRoomsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APICleanAllRoomsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014roomba.proto\"6\n\022CleanSelectedRooms\022\014\n\004" +
      "room\030\001 \001(\t\022\022\n\nroomnumber\030\002 \001(\005\"V\n\035APICle" +
      "anSelectedRoomsResponse\022\014\n\004room\030\001 \001(\t\022\022\n" +
      "\nroomnumber\030\002 \001(\005\022\023\n\013roompercent\030\003 \001(\005\"1" +
      "\n\rCleanAllRooms\022\014\n\004room\030\001 \001(\t\022\022\n\nroomnum" +
      "ber\030\002 \001(\005\"3\n\030APICleanAllRoomsResponse\022\027\n" +
      "\017responsemessage\030\001 \001(\t2\203\001\n\006roomba\022@\n\005cle" +
      "an\022\023.CleanSelectedRooms\032\036.APICleanSelect" +
      "edRoomsResponse(\0010\001\0227\n\010cleanAll\022\016.CleanA" +
      "llRooms\032\031.APICleanAllRoomsResponse(\001B\023\n\007" +
      "SB.grpcB\006RoombaP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CleanSelectedRooms_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CleanSelectedRooms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CleanSelectedRooms_descriptor,
        new java.lang.String[] { "Room", "Roomnumber", });
    internal_static_APICleanSelectedRoomsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_APICleanSelectedRoomsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APICleanSelectedRoomsResponse_descriptor,
        new java.lang.String[] { "Room", "Roomnumber", "Roompercent", });
    internal_static_CleanAllRooms_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CleanAllRooms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CleanAllRooms_descriptor,
        new java.lang.String[] { "Room", "Roomnumber", });
    internal_static_APICleanAllRoomsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_APICleanAllRoomsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APICleanAllRoomsResponse_descriptor,
        new java.lang.String[] { "Responsemessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
