// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lights.proto

package SB.grpc;

public interface SwitchOffAllLightsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SwitchOffAllLights)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string switchOffAll = 1;</code>
   */
  java.lang.String getSwitchOffAll();
  /**
   * <code>string switchOffAll = 1;</code>
   */
  com.google.protobuf.ByteString
      getSwitchOffAllBytes();
}
