// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lights.proto

package SB.grpc;

public interface SwitchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SwitchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 lightsstatus = 1;</code>
   */
  int getLightsstatus();

  /**
   * <code>int32 lightsroom = 2;</code>
   */
  int getLightsroom();
}
