# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alarm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='alarm.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\007SB.grpcB\005AlarmP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x61larm.proto\"+\n\x0e\x41larmOnRequest\x12\x19\n\x11\x61larmonreqmessage\x18\x01 \x01(\t\"/\n\x12\x41PIAlarmOnResponse\x12\x19\n\x11\x61larmonresmessage\x18\x01 \x01(\t\"-\n\x0f\x41larmOffRequest\x12\x1a\n\x12\x61larmoffreqmessage\x18\x01 \x01(\t\"1\n\x13\x41PIAlarmOffResponse\x12\x1a\n\x12\x61larmoffresmessage\x18\x01 \x01(\t2l\n\x05\x61larm\x12/\n\x07\x61larmon\x12\x0f.AlarmOnRequest\x1a\x13.APIAlarmOnResponse\x12\x32\n\x08\x61larmoff\x12\x10.AlarmOffRequest\x1a\x14.APIAlarmOffResponseB\x12\n\x07SB.grpcB\x05\x41larmP\x01\x62\x06proto3'
)




_ALARMONREQUEST = _descriptor.Descriptor(
  name='AlarmOnRequest',
  full_name='AlarmOnRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='alarmonreqmessage', full_name='AlarmOnRequest.alarmonreqmessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=58,
)


_APIALARMONRESPONSE = _descriptor.Descriptor(
  name='APIAlarmOnResponse',
  full_name='APIAlarmOnResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='alarmonresmessage', full_name='APIAlarmOnResponse.alarmonresmessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=107,
)


_ALARMOFFREQUEST = _descriptor.Descriptor(
  name='AlarmOffRequest',
  full_name='AlarmOffRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='alarmoffreqmessage', full_name='AlarmOffRequest.alarmoffreqmessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=154,
)


_APIALARMOFFRESPONSE = _descriptor.Descriptor(
  name='APIAlarmOffResponse',
  full_name='APIAlarmOffResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='alarmoffresmessage', full_name='APIAlarmOffResponse.alarmoffresmessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=205,
)

DESCRIPTOR.message_types_by_name['AlarmOnRequest'] = _ALARMONREQUEST
DESCRIPTOR.message_types_by_name['APIAlarmOnResponse'] = _APIALARMONRESPONSE
DESCRIPTOR.message_types_by_name['AlarmOffRequest'] = _ALARMOFFREQUEST
DESCRIPTOR.message_types_by_name['APIAlarmOffResponse'] = _APIALARMOFFRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AlarmOnRequest = _reflection.GeneratedProtocolMessageType('AlarmOnRequest', (_message.Message,), {
  'DESCRIPTOR' : _ALARMONREQUEST,
  '__module__' : 'alarm_pb2'
  # @@protoc_insertion_point(class_scope:AlarmOnRequest)
  })
_sym_db.RegisterMessage(AlarmOnRequest)

APIAlarmOnResponse = _reflection.GeneratedProtocolMessageType('APIAlarmOnResponse', (_message.Message,), {
  'DESCRIPTOR' : _APIALARMONRESPONSE,
  '__module__' : 'alarm_pb2'
  # @@protoc_insertion_point(class_scope:APIAlarmOnResponse)
  })
_sym_db.RegisterMessage(APIAlarmOnResponse)

AlarmOffRequest = _reflection.GeneratedProtocolMessageType('AlarmOffRequest', (_message.Message,), {
  'DESCRIPTOR' : _ALARMOFFREQUEST,
  '__module__' : 'alarm_pb2'
  # @@protoc_insertion_point(class_scope:AlarmOffRequest)
  })
_sym_db.RegisterMessage(AlarmOffRequest)

APIAlarmOffResponse = _reflection.GeneratedProtocolMessageType('APIAlarmOffResponse', (_message.Message,), {
  'DESCRIPTOR' : _APIALARMOFFRESPONSE,
  '__module__' : 'alarm_pb2'
  # @@protoc_insertion_point(class_scope:APIAlarmOffResponse)
  })
_sym_db.RegisterMessage(APIAlarmOffResponse)


DESCRIPTOR._options = None

_ALARM = _descriptor.ServiceDescriptor(
  name='alarm',
  full_name='alarm',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=207,
  serialized_end=315,
  methods=[
  _descriptor.MethodDescriptor(
    name='alarmon',
    full_name='alarm.alarmon',
    index=0,
    containing_service=None,
    input_type=_ALARMONREQUEST,
    output_type=_APIALARMONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='alarmoff',
    full_name='alarm.alarmoff',
    index=1,
    containing_service=None,
    input_type=_ALARMOFFREQUEST,
    output_type=_APIALARMOFFRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALARM)

DESCRIPTOR.services_by_name['alarm'] = _ALARM

# @@protoc_insertion_point(module_scope)
